#!/usr/bin/with-contenv bash

postconf -e myhostname="${MAILNAME}"
postconf -e mynetworks="${MYNETWORKS}"
postconf -e inet_protocols=all

postconf -M submission/inet="submission   inet   n   -   n   -   -   smtpd"
postconf -P "submission/inet/syslog_name=postfix/submission"
postconf -P "submission/inet/smtpd_tls_security_level=encrypt"
postconf -P "submission/inet/smtpd_etrn_restrictions=reject"
postconf -P "submission/inet/smtpd_sasl_type=dovecot"
postconf -P "submission/inet/smtpd_sasl_path=inet:${DOVECOT_HOST}:12345"
postconf -P "submission/inet/smtpd_sasl_security_options=noanonymous"
postconf -P "submission/inet/smtpd_sasl_local_domain=$myhostname"
postconf -P "submission/inet/smtpd_sasl_auth_enable=yes"
postconf -P "submission/inet/milter_macro_daemon_name=ORIGINATING"
postconf -P "submission/inet/smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject"
postconf -P "submission/inet/smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject"
postconf -P "submission/inet/smtpd_helo_restrictions=permit_mynetworks,permit"

postconf -M smtps/inet="smtps     inet  n       -       n       -       -       smtpd"
postconf -P "smtps/inet/syslog_name=postfix/smtps"
postconf -P "smtps/inet/smtpd_tls_wrappermode=yes"
postconf -P "smtps/inet/smtpd_sasl_auth_enable=yes"
postconf -P "smtps/inet/smtpd_reject_unlisted_recipient=no"
#postconf -P "smtps/inetsmtpd_client_restrictions=$mua_client_restrictions"
#postconf -P "smtps/inet/smtpd_helo_restrictions=$mua_helo_restrictions"
#postconf -P "smtps/inet/smtpd_sender_restrictions=$mua_sender_restrictions"
#postconf -P "smtps/inet/smtpd_recipient_restrictions="
postconf -P "smtps/inet/smtpd_relay_restrictions=permit_sasl_authenticated,reject"
#postconf -P "smtps/inet/ilter_macro_daemon_name=ORIGINATING"

# Configure postfix
postconf -e virtual_mailbox_domains=mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
postconf -e virtual_mailbox_maps=mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
postconf -e virtual_alias_maps=mysql:/etc/postfix/mysql-virtual-alias-maps.cf
postconf -e smtpd_recipient_restrictions="permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination,reject_invalid_hostname,reject_non_fqdn_hostname,reject_non_fqdn_sender,reject_non_fqdn_recipient,reject_unknown_sender_domain"

postconf -e smtpd_helo_required=yes
postconf -e smtpd_helo_restrictions="permit_mynetworks,reject_non_fqdn_helo_hostname,reject_unknown_helo_hostname,reject_invalid_helo_hostname,reject_non_fqdn_hostname, reject_invalid_hostname"
postconf -e strict_rfc821_envelopes=yes
postconf -e smtputf8_enable=no
postconf -e smtp_sasl_security_options=noanonymous
# rspamd config
postconf -e milter_protocol=6
postconf -e milter_mail_macros="i {mail_addr} {client_addr} {client_name} {auth_authen}"
postconf -e milter_default_action=accept
postconf -e smtpd_milters="inet:${RSPAMD_HOST}:11332"
postconf -e non_smtpd_milters="inet:${RSPAMD_HOST}:11332"

postconf -e virtual_transport="lmtp:${DOVECOT_HOST}:24"
postconf -e smtpd_sasl_path="inet:${DOVECOT_HOST}:12345"
postconf -e smtpd_sasl_type=dovecot
postconf -e smtpd_sasl_auth_enable=yes

postconf -e smtp_use_tls=yes
postconf -e smtp_tls_security_level=may
postconf -e smtp_tls_note_starttls_offer=yes
postconf -e smtpd_tls_security_level=may
postconf -e smtpd_tls_loglevel=1
postconf -e smtpd_tls_received_header=yes
postconf -e smtpd_tls_auth_only=yes
postconf -e smtpd_tls_cert_file="${SSL_CERT}"
postconf -e smtpd_tls_key_file="${SSL_KEY}"

postconf -e smtpd_discard_ehlo_keywords="silent-discard, dsn"
postconf -e soft_bounce=no
postconf -e message_size_limit=52428800
postconf -e mailbox_size_limit=0
postconf -e recipient_delimiter=-
postconf -e maximal_queue_lifetime=1h
postconf -e bounce_queue_lifetime=1h
postconf -e maximal_backoff_time=15m
postconf -e minimal_backoff_time=5m
postconf -e queue_run_delay=5m
postconf -e disable_vrfy_command=yes
postconf -e smtpd_delay_reject=yes
# RATE THROTTLING
postconf -e smtpd_client_connection_rate_limit=3
postconf -e smtpd_error_sleep_time=10s
postconf -e smtpd_soft_error_limit=4
postconf -e smtpd_hard_error_limit=4
postconf -e disable_vrfy_command=yes

newaliases

# Set up a relay host, if needed
if [ ! -z "$RELAYHOST" ]; then
	echo -en "‣ Forwarding all emails to $RELAYHOST"
	postconf -e "relayhost=$RELAYHOST"
fi

if [ "${FILTER_MIME}" == "true" ]
then
  postconf -e mime_header_checks=regexp:/etc/postfix/mime_header_checks
fi
